gpu_id: 0
multi_gpus: False
num_workers: 4
seed: 1

test:
  rate: 6.0
  thr: 0.05

dataset:
  name: 'sutd-traffic'
  test_question_pt: "./data/test_questions.pt"
  appearance_feat: "./data/appearance_feat_rn50.h5"
  object_feat: './data/object_test_feat' 
  save_dir: 'results/'
